# Generated by Django 4.0 on 2024-04-09 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Оценка')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'TestToUser',
                'verbose_name_plural': 'TestToUsers',
                'db_table': 'testtouser',
            },
        ),
    ]
