# Generated by Django 4.0 on 2024-04-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_testtouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instruction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.instruction', verbose_name='Инструкция'),
            preserve_default=False,
        ),
    ]
